name: green_genius
description: "A new Flutter project."
publish_to: 'none'

# Flutter 3.24.3
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  google_fonts: ^6.2.1
  package_info_plus: ^8.0.2
  get_storage: ^2.1.1
  on_process_button_widget: ^2.0.5
  on_popup_window_widget: ^0.0.13
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
#   flutter_launcher_icons: "^0.14.1"

# flutter_launcher_icons:
#   android: "ic_launcher"
#   ios: true
#   image_path: "lib/assets/icon.png"
#   remove_alpha_ios: true
#   min_sdk_android: 21 # android min sdk min:16, default 21
#   # flutter pub run flutter_launcher_icons

flutter:
  uses-material-design: true

  assets:
    - lib/assets/svg/
    - lib/assets/image/